# This is a stub file to help Pylance understand the shape of the compiled Rust module.
# It does not contain any implementation.

from typing import Any, Dict, Optional

class AoPValue:
    poly: Dict[str, int]
    base: int
    coeff: int

    def __init__(self, poly: Optional[Dict[str, int]] = ..., base: int = ..., coeff: int = ...) -> None: ...
    @staticmethod
    def from_number(n: int, base: int = ...) -> 'AoPValue': ...
    def to_numerical(self) -> int: ...
    def __repr__(self) -> str: ...
    def __add__(self, other: 'AoPValue') -> 'AoPValue': ...
    def __sub__(self, other: 'AoPValue') -> 'AoPValue': ...
    def __mul__(self, other: 'AoPValue') -> 'AoPValue': ...
    def __pow__(self, other: 'AoPValue') -> 'AoPValue': ...
    @staticmethod
    def int_to_key(exp_str: str) -> str: ...
